### ISSUE TITLE
Reaching minimum requirements

### ISSUE THREAD

**Issue by Bernadetten** [Bernadetten/Ray-Tracing#11]
- [x] Debugging

- [x] Drawing circles and polygons

- [ ] Rescale between mathematics <---> screen resolution

**Comment by MetalCreator666** [comment]
- [ ] Rescale between mathematics <---> screen resolution

**Comment by MetalCreator666** [comment]
Ik denk dat rescale voor minreq niet nodig is, want het werkt gewoon, t is wel nodig als we willen zoomen enzo, dus ik gooi m erbij als extra issue voor bonus.
