### ISSUE TITLE
Method: pixel in primitive.

### ISSUE THREAD

**Issue by Bernadetten** [Bernadetten/Ray-Tracing#17]

**Comment by MetalCreator666** [comment]
- [ ] For Circle

- [ ] For Polygon

**Comment by MetalCreator666** [comment]
Kweenie of het voor polygon wel nuttig is, het zijn volgens mij echt aardig wat berekeningen in tegenstelling tot voor een cirkel.

**Comment by MetalCreator666** [comment]
W8 nee we moeten deze methodes helemaal niet gaan proberen, want we gooien ze toch weg als we later met reflexiviteit gaan klooien
