### ISSUE TITLE
Rays need some sort of brightness?

### ISSUE THREAD

**Issue by Bernadetten** [Bernadetten/Ray-Tracing#25]
Diffuse gives back new rays with a new starting brightness, a crystall/glass circle too, since a part of it is transmitted and a part is absorped

There also needs to be some kind distance to amount of brightness function.. (needs to be impemented in diffuse functions and the RayHitsRefractiveCircle)

**Comment by MetalCreator666** [comment]
Jup, het idee hierachter is dat een ray z'n beginpunt dus normaal een lichtsource is, dus met de desbetreffende brightness en deze wordt steeds lager. Maar als deze ray ergens vanaf reflecteerd moeten de pixels die hij daarna tegenkomt de momentele "brightness van de ray" krijgen, dus bij wijze van spreke kan je de reflecting surface met het intersectionpoint zien als de nieuwe start van de ray (oftwel een soort van een tijdelijke lightsource) met de brightness die de intersectionpoint krijgt op basis van afstand tot daadwerkelijke lightsource.

**Comment by Bernadetten** [comment]
Brightness is added as a property in Ray

**Comment by Bernadetten** [comment]
met light attenuation gebruiken om de nieuwe start brightness te bereken.
